name: Build and push docker iamge

on:
  push:
    tags: 
      - 'v-*'  # for production deployment tag
      - 'canary-*' # for canary deployment tag
      - 'dev-*' # for dev deployment tag


jobs:
  build_and_push:
    uses: thienchuong/reusable-workflows/.github/workflows/build-push.yaml@main
    secrets: inherit
    with:
      aws-ecr: 267583709295.dkr.ecr.ap-southeast-1.amazonaws.com
      role-to-assume: arn:aws:iam::267583709295:role/github-oidc-role
